### PR TITLE
Added support to export intervals in form of laps in TCX

### PR DESCRIPTION
**Pull request by friekopter**
* TomTom Intervalls get exported as laps in TCX
* Intensity is set to active for work intervals, it is set to resting else
* Removed some unneeded code

This is tested for running and interval training in combination with Runalyze and works for me but needs more testing for other activity types.

### CODE REVIEW

**Comment by friekopter** [comment]
This may also solve Issue #45

**Comment by ryanbinns** [comment]
Thanks for the input. That looks good, except can you fix up your indenting please (no tabs, spaces only at 4-spaces per indent). Lines 261 - 269 are tabbed.

**Comment by friekopter** [comment]
Done.

**Comment by ryanbinns** [comment]
Excellent, thanks!

**Pull request merged**
