### PR TITLE
Added a new feature "--get-summaries" to retrieve Summary Activity Tracker information

### PR DESCRIPTION
**Pull request by derickr**
This new flag "--get-summaries" fetches the Summary Activity Tracker
information from the watch. These summaries are stored in the files 0x00b3xxxx.
These files use Google's protobuffer format, and hence need to be parsed by a
prototobuf library. The one that is used here is available as a package on
Debian and Ubuntu. Parts of the format were discovered by @scubajorgen,
with some of my additions.

The summaries information can be exported as CSV file too, by using
--get-summaries --set-formats=csv. I am not intending to write a tool akin to
ttbincnv at this moment.

This feature can be extended to also parse 0x00b1xxxx files, but that is a
future step.

I can imagine that I will at least need to add documentation for this feature,
but wanted to throw it our here so that you can see whether this is something
you'd like to accept.

### CODE REVIEW

**Comment by ryanbinns** [comment]
Thanks for the pull request. Unfortunately, one of my latest commits has adding some conflicts that need resolving - I fixed some of the code around where you've extracted creating the directory name in `do_get_activities_callback`. It shouldn't be too hard to add them into your code.

**Comment by derickr** [comment]
I'll have a look later and see if I can merge them.

I've been using this "in production" for a few weeks now, and I haven't run into any problems either.

**Comment by derickr** [comment]
I think I've rebased and merged this correctly. I haven't managed to run this yet, as I currently don't have my cable with me.

**Comment by derickr** [comment]
Hi @ryanbinns — would you like me to make other changes to this Pull Request?

**Comment by ryanbinns** [comment]
No, it's fine. I just merged it. Sorry it's taken so long; I lost track of it. Thanks for all the effort!

**Comment by ryanbinns** [comment]
I've had problems getting this to compile. It errors out with
```
/workspace/ttwatch/include/export.h:12:22: fatal error: protobuf.h: No such file or directory
```

Is this file a system include, or is it one that should be checked in, but was missed?

**Comment by derickr** [comment]
I had forgotten to add it before committing. I'd just added it.

**Comment by ryanbinns** [comment]
No worries. I just pulled it from your branch and it all works now. Thanks!

**Pull request merged**
