### PR TITLE
Use cumulative distance to calculate interval/lap distance

### LINKED ISSUE #159: Intervals wildly off
Some of my downloaded runs have crazy distances attributed to each lap in an interval run:

`<DistanceMeters>-296816.00</DistanceMeters>` and the like. As an example, [here's a link to a Strava activity](https://www.strava.com/activities/2299971800). As you can see, I've been to the sun and back!

All the other data about the run is fine, just the distances per lap is wrong (sometimes majorly in the negative, or 0m).

### PR DESCRIPTION
**Pull request by typhoon2099**
Reported distances are unreliable, this commit changes the code to calculate the interval distance based on the start/end cumulative distances.

Fixes #159

### CODE REVIEW

**Comment by ryanbinns** [comment]
I would prefer not to fix this in the ttbin reading code. The reason is that I would like the code to be able to read a ttbin file, then write to a new ttbin file and have it binary identical to the original. The best place to fix this would be in the file conversion routines.

**Comment by typhoon2099** [comment]
Righto, I'll make some changes shortly. I'm still unsure why the interval total distance is going wrong, I'd love to fix the root cause of the issue, but I can't seem to track it down. Unless of course that's what the watch is storing. This pull request is a bit of a plaster over the real issue.

**Comment by typhoon2099** [comment]
I've tracked down the issue to the data type used for `FILE_INTERVAL_FINISH_RECORD.type`. Changing this corrects the interval summaries in tcx files.

**Comment by ryanbinns** [comment]
Sorry for the delay, but thanks for tracking this down.

**Pull request merged**
