### PR TITLE
better smoothing for run cadence that accounts for pauses + GPS dropouts

### PR DESCRIPTION
**Pull request by dlenski**
I saw that you merged @onedayfishsale's patch for smoothed run cadence (#18). I had been doing something very similar, with a 20s time constant for smoothing, but slightly more sophisticated because it takes into account pauses and GPS dropouts rather than just assuming that exactly 1 s separates every pair of adjacent GPS points.

(Happens to me fairly often on trail runs :-))

### CODE REVIEW

**Comment by ryanbinns** [comment]
I was thinking about this a while ago. We may need to either use a faster time constant or add a bit more intelligence, as this will seriously affect analysing interval training, where the run cadence can change almost instantly when changing intervals.

Perhaps we could modify it to reset the smoothed cadence when an interval changes. What do you think?

**Comment by dlenski** [comment]
Interesting point about intervals. I haven't used this feature much so I don't know exactly how to handle it, but I think the idea would be to reset the cadence smoothing whenever a new interval starts, right?

Perhaps something like what I do when it is unpaused?

```
        case TAG_STATUS:
            if ((record->status.status == 2) && (lap_state == 0))
            {
                insert_pause = 1;
                /* reset cadence to avoid spikes when pausing */
                smooth_cadence = 0.0f;
                smooth_cadence_count = 0;
            }
            break;
```

Therefore:

```
        case TAG_INTERVAL_START:
            /* reset cadence to avoid spikes at interval boundaries */
            smooth_cadence = 0.0f;
            smooth_cadence_count = 0;
            break;
```

**Comment by onedayfishsale** [comment]
So, I get good interval results with my smoothing method, but that's not surprising since making my data look nice was really my only criterion. I'm glad someone else is looking at this too, and will run a few of my sample runs through to compare the various methods when I get a chance. I think there will be a difference with paused runs for the reason you explained.

**Comment by dlenski** [comment]
That's good to know, @onedayfishsale.

Your method and mine should be identical in the absence of GPS dropouts or
pauses (anything that violates the assumption that each GPS/cycle sample is
exactly 1 s after the previous).

I think resetting at the beginning of each internal would be helpful though.

Do you have any data showing a significant variation in steps per second
that you'd be willing to share? My input hardly seems to output meaningful
variation.

**Comment by ryanbinns** [comment]
Your solution looks nice and simple Dan; I think that would do the job nicely. I'll see if I get a chance to go for a run this afternoon and get some interval data I can test with it. Unfortunately, with a 1yo daughter and currently selling AND building a house, I may not have the chance for a while.

**Pull request closed without merging**
