### PR TITLE
Update README for different Spark/Runner2 product IDs and clarify unprivileged udev/usb setup a little

### PR DESCRIPTION
**Pull request by derickr**

### CODE REVIEW

**Comment by ryanbinns** [comment]
Thanks. That's great. Do you think it would be worthwhile to change the udev rule to include all the product IDs? Three nearly identical lines should do it.

**Comment by derickr** [comment]
Yes - I think so. I'll make a PR tomorrow.

**Comment by ryanbinns** [comment]
I decided I'd just do it. I've checked in a rules file that includes all three lines, so I'll update the `README.md` file to match and mention the file.

**Comment by ryanbinns** [comment]
I've updated the `README.md` file and also added a new rule to `Makefile` to automate the udev rule and usb group creation.

**Pull request merged**
