### PR TITLE
Preliminary fix for supporting file version 10

### LINKED ISSUE #133: Firmware 1.6 uses a new file format
The file format goes from "09" to "0A", which annoyingly changes some things in the TTBIN files that make ttbin/ttbincnv unable to parse the files.

I have discovered at least that this is changed in the header itself:

```
diff --git a/src/ttbin.c b/src/ttbin.c
index e554a16..16faca3 100755
--- a/src/ttbin.c
+++ b/src/ttbin.c
@@ -38,7 +38,7 @@ typedef struct __attribute__((packed))
 typedef struct __attribute__((packed))
 {
     uint16_t file_version;
-    uint8_t  firmware_version[3];
+    uint8_t  firmware_version[6];
```

There also seems to be a new tag in the file "0xFF" (position 0x1010C) which is not included in the tags-length structure and hence parsing fails through the condition:

```
343         /* find the length of this tag */                                                  
344         while ((index < file_header->length_count) && (file_header->lengths[index].tag != p.record->tag))
345             ++index;                                                                       
346         if ((index < file_header->length_count) && (file_header->lengths[index].tag == p.record->tag))
347             length = file_header->lengths[index].length;                                   
348         else
349         {                                                                                  
350             free_ttbin(file);
351             return 0;
352         }     
```

But I haven't managed to track down what to do with this. I've attached the new file as generated with the firmware - as you can see, the name of the file got mangled too (because of the header change).

[new-firmware-file.zip](https://github.com/ryanbinns/ttwatch/files/1320486/new-firmware-file.zip)

### PR DESCRIPTION
**Pull request by derickr**
Fixes #133

### CODE REVIEW

**Comment by mipapo** [comment]
But seems not to be backward compatibility

**Comment by derickr** [comment]
@mipapo - I tried with my older Runs, and they worked.

It would be really helpful if you could expand on "it doesn't work", by providing a file, what you've tried, what the outcome was, and what you expeced.

cheers,
Derick

**Comment by mipapo** [comment]
Cannot be converted to tcx 
[Running (2).ttbin.zip](https://github.com/ryanbinns/ttwatch/files/1328809/Running.2.ttbin.zip)

**Comment by mipapo** [comment]
Works perfectly!

**Comment by ryanbinns** [comment]
Thanks very much for investigating this. The code looks fine, but there are a couple of minor aesthetic things I'd like fixed before I merge. There are a couple lines that use tab indentation instead of spaces; please replace with spaces. Also please put opening braces on a new line instead of the end of the line, to match the existing code. After that, I'll be happy to merge.

**Comment by derickr** [comment]
Sure, will have a look at that. I also still need to test ttbinmod, as it should be able to re-create the right version'ed files after modification.

**Comment by scubajorgen** [comment]
Fyi: the new TomTom Fitnesspoints seem to be present in the record with tag 0x4A: 
1. Tag 0x4A (1 byte)
2. Timestamp (epoch seconds) (4 bytes)
3. Fitness point counter (2 bytes)
4. Fitness point counter (2 bytes)
(The 0x4B record is the new variable length record.)

**Comment by derickr** [comment]
@scubajorgen Happy to go look at that, and I also still need to fix the writing. Feel free to make a new issue and assign it to me? :-) (If @ryanbinns is OK with that)

**Pull request merged**
