### PR TITLE
+ new firmware 1.8.46

### PR DESCRIPTION
**Pull request by dlenski**
MANIFEST_DEFINITIONS appear to match other recent firmware versions, tested on my TomTom Runner

### CODE REVIEW

**Comment by DirkBri** [comment]
Hi,

this correction in ./ttwatch/manifest.txt I've made for my watch (1.8.46):

treadmill/metrics/left,29,e,1,0=clock,1=duration,2=distance,4=pace,5=avg_pace,6=speed,7=avg_speed,20=calories,21=heart,25=hr_zone
treadmill/metrics/right,30,e,1,0=clock,1=duration,2=distance,4=pace,5=avg_pace,6=speed,7=avg_speed,20=calories,21=heart,25=hr_zone
running/metrics/left,33,e,1,0=clock,1=duration,2=distance,4=pace,5=avg_pace,6=speed,7=avg_speed,20=calories,21=heart,25=hr_zone
running/metrics/right,34,e,1,0=clock,1=duration,2=distance,4=pace,5=avg_pace,6=speed,7=avg_speed,20=calories,21=heart,25=hr_zone

This here does not work for buzz, only for click (0,1) options/click,84,e,1,0=off,1=click+bz,2=click,3=buzz

I think, were is an other option for buzz ??

Kind regards, Dirk

**Comment by dlenski** [comment]
@DirkBri, you should post this as a diff rather than simply the new lines, since it's unclear what you're showing has changed here.

I don't have an HRM so I didn't test any of the HR-related changes, but `options/click` does not seem to have changed on my watch.

**Comment by DirkBri** [comment]
... OK, it's really quiet simple!

**Comment by ryanbinns** [comment]
@DirkBri I'll check against my watch when I get some time. Probably tomorrow. Did you check to see if the equivalent settings for cycling and freestyle have changed also?

@dlenski FYI, you don't actually need a HRM to test this; I don't have one either. If you enable the heart rate sensor in options, all the heart-rate related settings appear, regardless of whether you actually have one, presumably because the watch doesn't necessarily expect you to be wearing it until you start the activity.

**Comment by DirkBri** [comment]
No, I didn't check cycling and freestyle, because my watch supports only treadmill and running.

In case of options/click: On my watch, ttwatch only shows if "click" is enabled or not. It's independent from buzz. (I tried 85 - without success.)

**Comment by ryanbinns** [comment]
Sorry, I missed that you had a Runner, rather than a Multisport. The cycling, swimming and freestyle entries have changed as well. This is good. Previous versions had the same entries with different numerical values for different activities, which seemed odd to me (eg. calories was 7 for most things, but 8 for swimming). Now they're all the same between different activities.

Re click/buzz, you're right, it's been split into two entries. One for click, one for buzz. The buzz entry has been is entry 163, click stays at entry 84. Both are either 0 or 1 for off or on.

Thanks for letting me know. I have pushed changes to the code.

**Pull request merged**
