### PR TITLE
CMake build system + platform portability

### PR DESCRIPTION
**Pull request by hoheinzollern**
Hello,
I refactored a bit the code and moved to the CMake build system to be able to compile under Mac OS X. Maybe this could help also for the FreeBSD port that I saw you were attempting. Unfortunately for me, the code compiles under Mac and Linux, but on the latest OS X there are some bugs on libusb at the moment that make the tool unusable. I hope they get resolved though, and that this patch is also useful for you :)
Best,
Alessandro

### CODE REVIEW

**Comment by ryanbinns** [comment]
That seems to work ok, but can you change it so the library names don't have an extra 'lib' on the front? They're currently made as `liblibttwatch.a` and `liblibttbin.a`.

**Comment by hoheinzollern** [comment]
Now that's fixed, libttwatch is now called ttwatch-common: I couldn't call the library with the same name as the executable, and CMake automatically adds the prefix lib- to the library name.

**Comment by ryanbinns** [comment]
Actually, you can. Change it back to `libttwatch` then use
```set_target_properties(libttwatch PROPERTIES OUTPUT_NAME ttwatch)```
to change the filename (the `lib` is still added automatically). That would be better than changing it to `ttwatch-common`.

**Comment by hoheinzollern** [comment]
Oh yes, thanks for the suggestion, it's done now.

**Pull request merged**
